version: '3'

services:
  mysql57:
    image: mysql:5.7.22
    restart: always
    ports:
      - "40001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - mysql57-data:/var/lib/mysql

  mongodb36:
    image: mongo:3.6
    restart: always
    ports:
      - "40003:27017"
      - "40004:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb36-data:/data/db
      - mongodb36-configdb:/data/configdb

  redis32:
    image: redis:3.2
    restart: always
    ports:
      - "40008:6379"
    volumes:
      - redis32-data:/data

  crossbar:
    image: crossbario/crossbar
    restart: always
    volumes:
      - "$PWD/config/.crossbar:/node/.crossbar"
    labels:
      - "traefik.frontend.rule=Host:crossbar.dev.ecoffer.net"
    ports:
        - "8082:8080"

  jenkins:
    image: jenkinsci/blueocean
    restart: always
    user: root
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: app-test-env_jenkins_1


  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
      - "$PWD/config/registry/auth:/auth"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd

  Nginx1.14:
    image: nginx:1.14
    restart: always
    ports:
      - "8001:80"
    volumes:
      - "$PWD/config/nginx:/etc/nginx/conf.d"
      - "$PWD/code:/www/code"
      - "$PWD/logs:/www/logs"
    container_name: nginx

  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "44480:80"     # The HTTP port
      - "48080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # S
    container_name: traefik
  
networks:
  default:
    external:
      name: traefik_net

volumes:
  mysql57-data:
  mongodb36-data:
  mongodb36-configdb:
  redis32-data:
  registry-data:
  jenkins-data:
    external: true
